### PR TITLE
Bump nodejs to v12 and yarn to v1.22

### PR DESCRIPTION
**Pull request by samsondav**

### CODE REVIEW

**Comment by rupurt** [comment]
Last time I checked there was a problem with nodejs v12. Do these work now?

- https://github.com/axic/scrypt.js/issues/5
- https://www.pivotaltracker.com/story/show/168300258

**Comment by j16r** [comment]
Need to bump the tag in the `.github/actions`

**Comment by HenryNguyen5** [comment]
@samsondav  @rupurt @se3000  I checked today and those issues still haven't been resolved. One solution around this would be to replace `ganache-core` with `buidler` or `deth` which don't have `scrypt` as a dependency, which would allow us to perform this upgrade.

**Comment by rupurt** [comment]
I feel like we should look into alternatives. `nodejs` 10.x support ends in April 2021 which is only a year away.

**Comment by samsondav** [comment]
@rupurt @HenryNguyen5 Yes you are right, the build fails with nodejs 10.x.

Going to close this for now and leave you guys to come up with a solution :+1:

**Pull request closed without merging**
